# Generated by Django 4.1 on 2022-08-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='tag',
        ),
    ]
