# Generated by Django 4.1 on 2022-08-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0002_remove_comm_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lion_file/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comm',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lion_photo/%y/%m/%d/'),
        ),
    ]
